SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
ORDER BY CART_ID;

SELECT DISTINCT a.CART_ID
FROM CART_PRODUCTS a
JOIN CART_PRODUCTS b
  ON a.CART_ID = b.CART_ID
WHERE a.NAME = 'Milk'
  AND b.NAME = 'Yogurt'
ORDER BY a.CART_ID;
