-- 코드를 입력하세요
SELECT A.FOOD_TYPE, REST_ID, REST_NAME, A.FAVORITES
FROM (SELECT MAX(FAVORITES) AS FAVORITES, FOOD_TYPE
FROM REST_INFO
GROUP BY FOOD_TYPE) A INNER JOIN REST_INFO B
ON A.FAVORITES = B.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC;