-- 코드를 작성해주세요

WITH RECURSIVE ECOLI_TREE AS (
    -- 1세대 (루트)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 재귀적으로 세대 확장
    SELECT E.ID, E.PARENT_ID, T.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_TREE T
      ON E.PARENT_ID = T.ID
)
SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM ECOLI_TREE T
WHERE NOT EXISTS (
    SELECT 1 
    FROM ECOLI_DATA C 
    WHERE C.PARENT_ID = T.ID
)   -- 자식 없는 개체만
GROUP BY GENERATION
ORDER BY GENERATION;
