-- 코드를 작성해주세요
-- 1,2,3  / 4,5,6 / 7,8,9 / 10,11,12 (4분기)
SELECT B.QUARTER, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA A
JOIN
(SELECT CASE 
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
        WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN '4Q' ELSE 0 END AS QUARTER,
        ID
FROM ECOLI_DATA) B
ON A.ID = B.ID
GROUP BY B.QUARTER
ORDER BY B.QUARTER ASC;