-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_OUTS O
RIGHT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME ASC
LIMIT 3;
# JOIN 의 datetime = NULL, in의 datetime이 작은 