-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O LEFT JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = 2022 AND MONTH(O.PRODUCE_DATE) = 5 AND P.PRODUCT_NAME IS NOT NULL
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC;

