-- 코드를 입력하세요

SELECT M.MEMBER_NAME, L.REVIEW_TEXT, DATE_FORMAT(L.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW L
ON M.MEMBER_ID = L.MEMBER_ID
WHERE M.MEMBER_ID =
    (SELECT R.MEMBER_ID
    FROM REST_REVIEW R
    GROUP BY R.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
ORDER BY L.REVIEW_DATE ASC, L.REVIEW_TEXT ASC;