-- 코드를 작성해주세요

SELECT SUM(a.SCORE) AS SCORE, a.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM HR_GRADE a
LEFT JOIN HR_EMPLOYEES b
ON a.EMP_NO = b.EMP_NO
WHERE a.YEAR = 2022
GROUP BY a.EMP_NO
ORDER BY SUM(a.SCORE) DESC
LIMIT 1;