-- 코드를 작성해주세요

SELECT a.DEPT_ID AS DEPT_ID, b.DEPT_NAME_EN AS DEPT_NAME_EN, ROUND(AVG(SAL),0) AS AVG_SAL
FROM HR_EMPLOYEES a
LEFT JOIN HR_DEPARTMENT b
ON a.DEPT_ID = b.DEPT_ID
GROUP BY DEPT_ID, DEPT_NAME_EN
ORDER BY AVG(SAL) DESC;